cleanup

diff --git a/.github/workflows/iso.yml b/.github/workflows/iso.yml
--- a/.github/workflows/iso.yml
+++ b/.github/workflows/iso.yml
@@ -14,13 +14,6 @@ name: Build ISOs
 
 on:
   workflow_dispatch:
-  # pull_request:
-  #   branches:
-  #     - live
-  #   paths:
-  #     - './.github/workflows/config/iso.toml'
-  #     - './.github/workflows/config/image.toml'
-  #     - './.github/workflows/iso-hardened '
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
@@ -66,24 +59,48 @@ jobs:
 
       - name: Set target image
         shell: bash
-        run: sed -i 's/TARGETIMAGE/${{ matrix.image }}/g' ./.github/workflows/config/iso.toml
+        env:
+          IMAGE_NAME: ${{ matrix.image }}
+        run: sed -i 's/TARGETIMAGE/${{ env.IMAGE_NAME }}/g' ./.github/workflows/config/iso.toml
 
-      - name: Pull image
+      - name: Set variant
         shell: bash
-        run: sudo podman pull "ghcr.io/secureblue/${{ matrix.image }}:latest"
+        id: set_variant
+        run: |
+          case "$IMAGE_NAME" in
+            *silverblue*)
+              VARIANT="silverblue"
+              ;;
+            *kinoite*)
+              VARIANT="kinoite"
+              ;;
+            *sericea*)
+              VARIANT="sericea"
+              ;;
+            *cosmic*)
+              VARIANT="cosmic"
+              ;;
+            *)
+              echo "Error: Unknown image variant: $IMAGE_NAME" >&2
+              exit 1
+              ;;
+          esac
+
+          echo "VARIANT=${VARIANT}" >> ${GITHUB_OUTPUT}
 
       - name: Build ISO
-        uses: jasonn3/build-container-installer@main
+        uses: jasonn3/build-container-installer@d77e9563739921c2f93de778d4fbad854f52d389 # main
         id: iso_build
         env:
           IMAGE_NAME: ${{ matrix.image }}
+          VARIANT: ${{ steps.set_variant.outputs.variant }}
         with:
           arch: x86_64
           image_name: ${{ env.IMAGE_NAME}}
           image_repo: ghcr.io/secureblue
           image_tag: latest
           version: 42
-          variant: silverblue
+          variant: ${{ env.VARIANT }}
           iso_name: ${{ env.IMAGE_NAME }}.iso
 
 
@@ -91,43 +108,50 @@ jobs:
         id: rename
         shell: bash
         env:
-          OUTPUT_DIRECTORY: ${{ steps.iso_build.outputs.iso_path }}
           IMAGE_NAME: ${{ matrix.image }}
+          ISO_SIGNING_KEY: ${{ secrets.ISO_SIGNING_KEY }}
         run: |
           sudo chown $(whoami) "${IMAGE_NAME}.iso" "${IMAGE_NAME}.iso-CHECKSUM"
 
-          HASH=$(cat "${IMAGE_NAME}.iso-CHECKSUM" | cut -d ' ' -f1)
-          ISO_SIZE=$(stat -c %s "${IMAGE_NAME}.iso")
-          ISO_FILE_NAME="${IMAGE_NAME}.iso"
+          TARGET_OUTPUT_DIRECTORY="$(pwd)/output"
+          ISO_NAME="${IMAGE_NAME}.iso"
+          CHECKSUM_NAME="${ISO_NAME}-CHECKSUM"
+          mv "${ISO_NAME}" "$TARGET_OUTPUT_DIRECTORY"
+          mv "${CHECKSUM_NAME}" "$TARGET_OUTPUT_DIRECTORY"
+          cd "$TARGET_OUTPUT_DIRECTORY"
+
+          HASH=$(cat "${CHECKSUM_NAME}" | cut -d ' ' -f1)
+          ISO_SIZE=$(stat -c %s "${ISO_NAME}")
+          ISO_FILE_NAME="${ISO_NAME}"
           {
             echo "# $ISO_FILE_NAME: $ISO_SIZE bytes"
             echo "SHA256 ($ISO_FILE_NAME) = $HASH"
-          } > "${IMAGE_NAME}.iso-CHECKSUM"
+          } > "${CHECKSUM_NAME}"
 
           echo "CHECKSUM contents"
-          cat "${IMAGE_NAME}.iso-CHECKSUM"
+          cat "${CHECKSUM_NAME}"
           echo
 
-          echo "${{ secrets.ISO_SIGNING_KEY }}" | gpg --import
+          echo "${ISO_SIGNING_KEY}" | gpg --import
 
           echo "Signing the ISO"
-          gpg --clearsign -u 26B4463ED8F313BC7E3FBDF9D9223AF0F47B3E41 "${IMAGE_NAME}.iso-CHECKSUM"
-          mv "${IMAGE_NAME}.iso-CHECKSUM.asc" "${IMAGE_NAME}.iso-CHECKSUM"
+          gpg --clearsign -u 26B4463ED8F313BC7E3FBDF9D9223AF0F47B3E41 "${CHECKSUM_NAME}"
+          mv "${CHECKSUM_NAME}.asc" "${CHECKSUM_NAME}"
 
           echo "Signed CHECKSUM contents"
-          cat "${IMAGE_NAME}.iso-CHECKSUM"
+          cat "${CHECKSUM_NAME}"
           echo
 
           # validate signature
           curl -O "https://repo.secureblue.dev/secureblue.gpg"
           gpg --no-default-keyring --keyring ./secureblue-keyring.gpg --import secureblue.gpg
 
-          if ! gpgv --keyring ./secureblue-keyring.gpg "${IMAGE_NAME}.iso-CHECKSUM"; then
+          if ! gpgv --keyring ./secureblue-keyring.gpg "${CHECKSUM_NAME}"; then
               echo "CHECKSUM signature verification FAILED! Exiting..."
               exit 1
           fi
 
-          if ! sha256sum --ignore-missing -c "${IMAGE_NAME}.iso-CHECKSUM"; then
+          if ! sha256sum --ignore-missing -c "${CHECKSUM_NAME}"; then
               echo "CHECKSUM verification FAILED! Exiting..."
               exit 1
           fi
@@ -135,7 +159,7 @@ jobs:
           rm ./secureblue-keyring.gpg~
           rm secureblue.gpg
 
-          echo "output-directory=${OUTPUT_DIRECTORY}" >> ${GITHUB_OUTPUT}
+          echo "output-directory=${TARGET_OUTPUT_DIRECTORY}" >> ${GITHUB_OUTPUT}
 
       - name: Upload ISO and Checksum to Job Artifacts
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
@@ -156,7 +180,8 @@ jobs:
           RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.ISOS_SECRET_ACCESS_KEY }}
           RCLONE_CONFIG_R2_REGION: auto
           RCLONE_CONFIG_R2_ENDPOINT: ${{ secrets.ISOS_ENDPOINT }}
+          OUTPUT_DIRECTORY: ${{ steps.rename.outputs.output-directory }}
           SOURCE_DIR: .
         run: |
-          rclone copy "${{ steps.rename.outputs.output-directory }}" R2:isos 
+          rclone copy "${OUTPUT_DIRECTORY}" R2:isos 
       
